{
 "title": "MicroProfile Demo",
 "description": "Metrics on the MicroProfile Demo service",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Profiling",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=\"red:7080\",job=\"red\"}"
    }
   ]
  },
  {
   "title": "Membership Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application:membership_requests{instance=\"localhost:8080\",job=\"Membership\"}",
     "legendFormat": "get member"
    },
    {
     "expr": "application:membership_created{instance=\"localhost:8080\",job=\"Membership\"}",
     "legendFormat": "create member"
    },
    {
     "expr": "application:membership_deleted{instance=\"localhost:8080\",job=\"Membership\"}",
     "legendFormat": "delete member"
    }
   ]
  },
  {
   "title": "User",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=\"localhost:9443\",job=\"User\"}"
    }
   ]
  },
  {
   "title": "Membership",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=\"yellow:8080\",job=\"yellow\"}"
    }
   ]
  },
  { "title": "Legoland", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Heap memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base:memory_used_heap_bytes{instance=\"localhost:8080\",job=\"Membership\"}",
     "legendFormat": "Membership"
    },
    {
     "expr": "base:memory_used_heap_bytes{instance=\"localhost:7080\",job=\"Profiling\"}",
     "legendFormat": "Profiling"
    },
    {
     "expr": "base:memory_used_heap_bytes{instance=\"localhost:9443\",job=\"User\"}",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "System load average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base:cpu_system_load_average{instance=\"localhost:8080\",job=\"Membership\"}",
     "legendFormat": "Membership"
    },
    {
     "expr": "base:cpu_system_load_average{instance=\"localhost:7080\",job=\"Profiling\"}",
     "legendFormat": "Profiling"
    },
    {
     "expr": "base:cpu_system_load_average{instance=\"localhost:9443\",job=\"User\"}",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "Loaded classes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base:classloader_current_loaded_class_count{instance=\"localhost:8080\",job=\"Membership\"}",
     "legendFormat": "Membership"
    },
    {
     "expr": "base:classloader_current_loaded_class_count{instance=\"localhost:7080\",job=\"Profiling\"}",
     "legendFormat": "Profiling"
    },
    {
     "expr": "base:classloader_current_loaded_class_count{instance=\"localhost:9443\",job=\"User\"}",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "Thread count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base:thread_count{instance=\"localhost:8080\",job=\"Membership\"}",
     "legendFormat": "Membership"
    },
    {
     "expr": "base:thread_count{instance=\"localhost:7080\",job=\"Profiling\"}",
     "legendFormat": "Profiling"
    },
    {
     "expr": "base:thread_count{instance=\"localhost:9443\",job=\"User\"}",
     "legendFormat": "User"
    }
   ]
  }
 ]
}