{
 "title": "Membership",
 "description": "Metrics on the Membership service",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application:membership_requests_time_mean_seconds{instance=\"yellow:8080\",job=\"yellow\"}"
    }
   ]
  },
  {
   "title": "Member requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application:membership_requests{instance=\"yellow:8080\",job=\"yellow\"}",
     "legendFormat": "requests"
    },
    {
     "expr": "application:membership_created{instance=\"yellow:8080\",job=\"yellow\"}",
     "legendFormat": "created"
    },
    { "expr": "application:membership_deleted", "legendFormat": "deleted" }
   ]
  },
  {
   "title": "Heap memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base:memory_used_heap_bytes{instance=\"yellow:8080\",job=\"yellow\"}"
    },
    {
     "expr": "base:memory_max_heap_bytes{instance=\"yellow:8080\",job=\"yellow\"}"
    }
   ]
  },
  {
   "title": "System load average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base:cpu_system_load_average{instance=\"yellow:8080\",job=\"yellow\"}"
    }
   ]
  },
  {
   "title": "Thread count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base:thread_count{instance=\"yellow:8080\",job=\"yellow\"}"
    }
   ]
  },
  {
   "title": "Loaded classes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base:classloader_current_loaded_class_count{instance=\"yellow:8080\",job=\"yellow\"}"
    }
   ]
  }
 ]
}